### ISSUE TITLE
Layout import and export commands aren't working

### ISSUE THREAD

**Issue by baizmandesign** [OnTheGoSystems/toolset-cli#20] opened 2021-04-16 00:24 UTC
@zaantar Layout import and export commands aren't working. The culprit seems to be that my patch for [layouts/inc/theme/wpddl.theme-support.class.php](https://gist.github.com/baizmandesign/8d56f459f02ed4842402142449db13ae) wasn't implemented, nor was my [slight alteration to layouts/classes-auto/wpddl-options.class.php](https://github.com/OnTheGoSystems/toolset-cli/issues/6#issuecomment-761592565).

Do you know when these changes can be incorporated into the Layouts plugin? I've just written a great shell script to export types, views, and layouts, copy them to a remote server via scp, and then import them—but it doesn't handle the layouts! :-)

**Comment by zaantar** [comment] 2021-04-19 13:32
@baizmandesign, this is weird, sorry for asking this but are you sure you're comparing against the most recent version of Layouts? Because this is what I see:

![image](https://user-images.githubusercontent.com/6987234/115244751-878d2180-a124-11eb-95f9-727bd0ca03c3.png)
 
The changes are clearly present, albeit in a bit adjusted form compared to what you suggested. But this has been merged and should totally be a part of Layouts 2.6.9. 🤔

**Comment by baizmandesign** [comment] 2021-04-19 13:56
@zaantar Thanks for your response. I checked the version of the Layouts plugin that I've got on my toolset-cli testing instance, and it's only on 2.6.8. The WP dashboard isn't prompting me to update to 2.6.9, either.

I also logged into my account on Toolset.com to look at the versions of the plugins on all of my registered sites, and nearly all of them were using a slightly older version of the Types plugin, too. (The tabular overview on the Sites page no longer displays the Layouts plugin version, yikes! Makes sense since it's legacy.) The WP dashboard wasn't prompting me to upgrade either the Types plugin or Layouts. When I went to the commercial plugins tab (/wp-admin/plugin-install.php?tab=commercial) and clicked "Check for updates," only then did it identify newer versions of the plugins and offer links to update them. (The WP dashboard says I'm supposed to receive automatic updates until March 13, 2022.) 

The bigger issue is that none of my websites—either the instances I develop on locally or the production websites that exist on commercial web hosts—are prompting me to update to the latest versions of any of the Toolset plugins. And that's why I didn't have the latest version of Layouts. Is my next step to open a ticket with Toolset Support on toolset.com?

Oh, and feel free to close this issue!

**Comment by zaantar** [comment] 2021-04-19 14:15
@baizmandesign actually, that's not a bug but a feature 😁 ... We're rolling out updates to clients in batches so that we don't hit 100% of our clients if there is, god forbid, any serious issue that we've missed. So, unless you are building a new site or you manually hit the "Check for updates" button, it might take a little while before you get an update notification.

**Closed as completed** 2021-04-19 14:16 UTC

**Comment by baizmandesign** [comment] 2021-04-19 14:19
@zaantar Thanks for explaining the situation. I thought all of my websites were broken or I was going crazy!
